// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUUMZBTWgA_SZ8gpR2i1vJvA3h7NiLsC4',
    appId: '1:954441175115:web:c62e83a135fb919e277dce',
    messagingSenderId: '954441175115',
    projectId: 'solar-management-bb0a3',
    authDomain: 'solar-management-bb0a3.firebaseapp.com',
    storageBucket: 'solar-management-bb0a3.firebasestorage.app',
    measurementId: 'G-5ZSKB0WVCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNeWU57Rwrsc7jKde1WONU5MotUecyo8',
    appId: '1:954441175115:android:02d3d778e30f24e2277dce',
    messagingSenderId: '954441175115',
    projectId: 'solar-management-bb0a3',
    storageBucket: 'solar-management-bb0a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6JS7mka92gtvA5CJzPNQvXH1qfPbmxPg',
    appId: '1:954441175115:ios:faff7b745b555d1e277dce',
    messagingSenderId: '954441175115',
    projectId: 'solar-management-bb0a3',
    storageBucket: 'solar-management-bb0a3.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6JS7mka92gtvA5CJzPNQvXH1qfPbmxPg',
    appId: '1:954441175115:ios:faff7b745b555d1e277dce',
    messagingSenderId: '954441175115',
    projectId: 'solar-management-bb0a3',
    storageBucket: 'solar-management-bb0a3.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUUMZBTWgA_SZ8gpR2i1vJvA3h7NiLsC4',
    appId: '1:954441175115:web:081759449374a945277dce',
    messagingSenderId: '954441175115',
    projectId: 'solar-management-bb0a3',
    authDomain: 'solar-management-bb0a3.firebaseapp.com',
    storageBucket: 'solar-management-bb0a3.firebasestorage.app',
    measurementId: 'G-GP29Y87WTS',
  );
}
